### ISSUE TITLE
Вопрос по поводу обертки для питона

### ISSUE THREAD

**Issue by Quolyk** [mbuzdalov/pads-io#2]
Привет. Зачем ты в примере используешь `with openedu_io() as io:`, тогда получится, что вся программа уже будет с отступом, не легче ли просто `io = openedu_io()`.

**Comment by mbuzdalov** [comment]
Тогда этот `io` надо будет в конце руками закрывать. А если не закрыть, то выходные данные могут уйти в файл не до конца. `with` в этом плане довольно удобен.

**Comment by Quolyk** [comment]
Согласен, прочитал подробнее про контекстные менеджеры
